"""Schemas for ``*.arch.json``, the normalized resource JSON and the icon catalog."""

from .common import SCHEMA_VERSION, CamelModel, Tag
from .diagram import (
    ArrowStyle,
    BorderSide,
    Diagram,
    DiagramMeta,
    Edge,
    EdgeData,
    EdgeRouter,
    GroupNode,
    GroupStyle,
    LayoutMode,
    LayoutOptions,
    LineStyle,
    Node,
    Origin,
    Position,
    ResourceMount,
    ResourceNode,
    ResourceNodeData,
    ResourceScope,
    ShapeNode,
    Size,
    TextNode,
    Viewport,
)
from .export import ExportBundle, ExportOptions
from .icons import IconCatalog, IconEntry, IconGroup, IconScopes
from .resource import (
    Inventory,
    InventoryEntry,
    Lifecycle,
    NormalizedResource,
    Relation,
    Row,
    Section,
)

__all__ = [
    "SCHEMA_VERSION",
    "ArrowStyle",
    "BorderSide",
    "CamelModel",
    "Diagram",
    "DiagramMeta",
    "Edge",
    "EdgeData",
    "EdgeRouter",
    "ExportBundle",
    "ExportOptions",
    "GroupNode",
    "GroupStyle",
    "IconCatalog",
    "IconEntry",
    "IconGroup",
    "IconScopes",
    "Inventory",
    "InventoryEntry",
    "LayoutMode",
    "LayoutOptions",
    "Lifecycle",
    "LineStyle",
    "Node",
    "NormalizedResource",
    "Origin",
    "Position",
    "Relation",
    "ResourceMount",
    "ResourceNode",
    "ResourceNodeData",
    "ResourceScope",
    "Row",
    "Section",
    "ShapeNode",
    "Size",
    "Tag",
    "TextNode",
    "Viewport",
]
